### ISSUE TITLE
B.cpp and C.cpp are basically the same

### ISSUE THREAD

**Issue by Vadimuh** [siliviu/Jotto-Problem#2]
Why not take the file of words to parse as a command line argument?
Alternatively, if you insist on hardcoding the filename into the executable - you could have a Makefile and pass in the filename
as an argument to Make, which will then pass it as an argument to the compiler
https://stackoverflow.com/questions/62460059/how-to-define-value-for-c-preprocessor-directives-during-compile-time
https://stackoverflow.com/questions/2826029/passing-additional-variables-from-command-line-to-make

**Comment by siliviu** [comment]
Well, I originally did take the args as the file names but I ended up hardcording the maximum number of valid words for performance reasons (bitset) and then got rid of it. I could just take the bigger value for the array and not hardcore the file names but I ended up not doing that and just making 2 separate files (partly to make it easier if anyone else wants to run it).
