### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by NicolasGoeddel** [siliviu/Jotto-Problem#3]
After a `make B` on an Ubuntu 22.04 and executing `./B.exe` I only get a "Segmentation fault".
The same happens with `C.exe`.

Btw: Why has it the extension `.exe`? That's quite uncommon on Linux systems. Just call it `B` and `C`. :-) 

More information:
```
nicolas@Rocky:~/git/Jotto-Problem$ gdb C.exe 
GNU gdb (Ubuntu 12.0.90-0ubuntu1) 12.0.90
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from C.exe...
(gdb) run
Starting program: /home/nicolas/git/Jotto-Problem/C.exe 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000055555555675d in main ()
(gdb) q
A debugging session is active.

	Inferior 1 [process 305819] will be killed.

Trotzdem beenden? (y or n) y
```

**Comment by siliviu** [comment]
It's due to the stack limit set on your machine. It's compiling it with 256MB reserved for stack, which is admittedly overkill. I'lll lower the stack size and also make the makefile (temporarily) increase the stack size in order to run it. As for the .exe, I first compiled this on Windows and didn't change it when I copied the command over

**Comment by siliviu** [comment]
I should have fixed it. I am curious, so please let me know how fast it runs on your machine.

**Comment by NicolasGoeddel** [comment]
It still only shows a Segmentation Fault. :thinking:

I have an "AMD Ryzen 7 5800X 8-Core Processor" here if that helps you somehow figuring out the problem.
Or is there anything else I could check by myself beyond changing the `stack-size`?

**Comment by NicolasGoeddel** [comment]
I figured it out. `ulimit -s` told me my stack size is only 8192. I increased it to 65536 and now the programm runs.

Here are my times:
```
nicolas@Rocky:~/git/Jotto-Problem$ time ./B | tail -n2
10
0.0950948 s

real	0m0,104s
user	0m1,100s
sys	0m0,078s
nicolas@Rocky:~/git/Jotto-Problem$ time ./C | tail -n2
654
0.154618 s

real	0m0,164s
user	0m1,477s
sys	0m0,104s
```

**Comment by Vadimuh** [comment]
Using Ubuntu 20.04.3 in WSL2
I'm getting segfaults trying to run it. Increasing stack size limit didn't fix it for me. Tried editing /etc/security/limits.conf - didn't work in changing stack size limit. Tried doing `sudo sh -c "ulimit -s 65536 && exec su $LOGNAME"` and then building and
executing it - still getting segfaults. Tried `sudo su root` then `ulimit -s 65536` then built and attempted executing it still as root - didn't work.

**Comment by siliviu** [comment]
`ulimit -s 65536` should do the job. Check the stack actually increases after you do it (`ulimit -s`)
Alternatively, you can move the bitset declaration above the main function. That should make it not exceed the default stack size but allocating on heap should be slower.

**Comment by Vadimuh** [comment]
It didn't do the job. Here's a recording: https://asciinema.org/a/8uDVWMHzYK8J9KRJhdaJ9kRXU
For this recording I had set up a brand new Ubuntu 22.04 VM in WSL2.
